var species =["Acer campestre",
"Acer cappadocicum",
"Acer griseum",
"Acer negundo",
"Acer platanoides",
"Acer pseudoplatanus",
"Acer saccharinum",
"Aesculus × carnea",
"Aesculus hippocastanum",
"Ailanthus altissima",
"Alnus glutinosa",
"Amelanchier lamarckii",
"Betula albosinensis",
"Betula ermanii",
"Betula jacquemontii",
"Betula nigra",
"Betula pendula",
"Betula pendula Dalecarlica",
"Betula utilis",
"Carpinus betulus",
"Castanea sativa",
"Catalpa bignonioides",
"Cedrus atlantica",
"Cedrus deodara",
"Chamaecyparis lawsoniana",
"Corylus colurna",
"Cotoneaster",
"Crataegus monogyna",
"Cupressus × leylandii",
"Cupressus nootkatensis",
"Eucalyptus",
"Eucalyptus regnans",
"Fabaceae",
"Fagus sylvatica",
"Fraxinus excelsior",
"Fraxinus ornus",
"Fraxinus pendula",
"Ilex aquifolium",
"Juniperus communis",
"Koelreuteria",
"Laburnum anagyroides",
"Larix decidua",
"Laurus nobilis",
"Liquidambar",
"Liriodendron",
"Magnolia",
"Malus",
"Malus sylvestris",
"Metasequoia glyptostroboides",
"Nothofagus",
"Parrotia persica",
"Picea abies",
"Picea pungens",
"Pinus contorta",
"Pinus nigra",
"Pinus radiata",
"Pinus sylvestris",
"Platanus × acerifolia",
"Populus alba",
"Populus balsamifera",
"Prunus",
"Prunus avium",
"Prunus padus",
"Pterocarya fraxinifolia",
"Pyrus communis",
"Quercus buckleyi",
"Quercus cerris",
"Quercus ilex",
"Quercus variabilis",
"Salix babylonica",
"Salix caprea",
"Salix triandra",
"Sequoiadendron giganteum",
"Sorbus × intermedia",
"Sorbus mitchellii",
"Syringa vulgaris",
"Taxus baccata",
"Thuja plicata",
"Tilia cordata",
"Tilia platyphyllos",
"Tilia tomentosa Petiolaris",
"Ulmus procera",
"unclear"]